### ISSUE TITLE
Missing pull-requests permissions

### ISSUE THREAD

**Issue by TrayserCassa** [octo-sts/app#351]
Hey,
maybe I'm wrong but currently we can't use this configuration.
```
issuer: https://token.actions.githubusercontent.com
subject: repo:<org>/<repo>:ref:refs/heads/main

permissions:
  contents: write
  issues: write
  pull-requests: write
```
It seems like the `pull-requests` I updated later on is not working as it should. So it worked before adding the `pull-requests` permissions. After adding it I get an `unable to parse trust policy found for "<sts-file>"`. 

Also a side issue is that there is a cache I think? Because it takes sometimes after I removed the permission and test again. A file rename for the sts is helping here.
