### ISSUE TITLE
Create an action to encapsulate the exchange

### ISSUE THREAD

**Issue by mattmoor** [octo-sts/app#5]
```yaml
    steps:
    - id: octo-sts
      run: |
        THIS_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=octo-sts" | jq -r .value)
        THAT_TOKEN=$(curl -H "Authorization: Bearer ${THIS_TOKEN}" "https://octo-sts-j2wqachcbq-uc.a.run.app/sts/exchange?scope=mattmoor/test-bed&identity=bar" | jq -r .token)
        echo "::add-mask::${THAT_TOKEN}"
        echo "token=${THAT_TOKEN}" >> "$GITHUB_OUTPUT"

    - env:
        GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: |
        gh repo list
```
