### ISSUE TITLE
Do not match on `email` for Google organization membership

### ISSUE THREAD

**Issue by matthiasr** [octo-sts/app#802]
[In their Identity docs](https://developers.google.com/identity/openid-connect/openid-connect#obtainuserinfo), Google loudly and repeatedly discourage using the `email` claim as identification, or as guarantee that someone is a member of the organization.

There may be cases when it's really what you want, but I find it a bit dangerous to have the first and only example of identifying someone by their Google identity use `email`. Could the example in the README use

```yaml
claims:
  hd: chainguard.dev
```

instead?

**Comment by mattmoor** [comment]
I'd probably rather use a stricter subject pattern, even if the gaia IDs are fictional:
```yaml
issuer: https://accounts.google.com
subject_pattern: '(1234|5678)'
claim_pattern:
  foo: '.*bar.*' 

permissions:
  contents: read
```
