### ISSUE TITLE
Security: Privilege Escalation Vulnerability in Policy Management

### ISSUE THREAD

**Issue by salekseev** [octo-sts/app#887]
## Summary
A vulnerability exists in octo-sts that allows for privilege escalation through policy file modification. Users or workflows granted `contents: write` permission to a repository can modify policy files to elevate their own privileges (e.g., from `contents: write` to `contents: admin`). 

## Steps to Reproduce
1. Repository A's admin creates a policy granting Repository B's owner `contents:write` permission to Repository A, for example:

```yaml
issuer: https://token.actions.githubusercontent.com
subject: repo:org1/repo-b:ref:refs/heads/main

permissions:
  contents: write
```

3. Repository B's owner uses their token with `contents:write` permission to access Repository A
4. They modify the policy file in Repository A to change their permission level from just `contents:write` to add `administration:read` like:

```yaml
issuer: https://token.actions.githubusercontent.com
subject: repo:org1/repo-b:ref:refs/heads/main

permissions:
  contents: write
  administration: read
```

6. Repository B's owner now has admin-level read access to Repository A 

## Impact
This vulnerability allows for unauthorized privilege escalation, breaking the intended security model. A user with limited write access can gain admin permissions to repositories, potentially compromising sensitive data or further expanding access to other actors.

## Additional Context
This issue was discovered during security testing of federated access implementation in our organization. We believe this is a critical security issue that requires attention as it undermines the core access control model.
